### ISSUE TITLE
Scroller Stuck at Right

### ISSUE THREAD

**Issue by KingGeneral** [yucatio/yucatio.github.io#1]
I found bug with the scroller, 
(yucatio-my-master-nov-5)

Re-produce bug : 
- scroll to the right
- Press zoom (+)
- Scroll stuck at certain point , (if not using mouse scroll)
---- Now, must click button to navigate to right. or use mouse scroll
---- update : not work well when user drag using the ball/toggle there.

Tested in : Chrome , Mozilla Firefox, Edge 

@yucatio

Issue created because  this : (after analysis of scroller issue)
```
Commits on Jan 25, 2016 - @Yucatio -  785337c
disable useless button  …
rmove core.Nvigation.panelMargin
```
Here the Screenshot : (Screenshot version : yucatio-my-master-nov-5)
![issue-yucatio-my-master-nov-5](https://cloud.githubusercontent.com/assets/9468485/21256876/717eb804-c3a7-11e6-9efa-19984b05e29c.png)

**Comment by yucatio** [comment]
Hi KingGeneral.
Thank you for reporting bug and investigation.
I'll fix this issue.

**Comment by yucatio** [comment]
Hi I fix the code. Now it working properly. Please check it.
From next time, you can create new issue from https://github.com/yucatio/jQuery.Gantt/issues
I know previously issue tab was hidden. It was unintended. But now it is visible.

**Comment by KingGeneral** [comment]
Thank you very much yucatio 🍭, that was so clean solution.

By the way, thanks for opening the hidden issue tab on [yucatio/jQuery.Gantt/issues](https://github.com/yucatio/jQuery.Gantt/issues), next will post there. ❤️
